name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Permisos necesarios
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Job de testing
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type check
      run: npm run type-check
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm test

  # Job de build y deploy
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_SITE_URL: https://jusdorado.github.io/portafolio-justo
        
    - name: Verify build output
      run: |
        echo "Checking if out directory exists..."
        ls -la
        if [ -d "out" ]; then
          echo "✅ out directory found"
          ls -la out/
        else
          echo "❌ out directory not found"
          exit 1
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './out'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
